instruction: "Instruction: Please try to answer the single-answer multiple choice question below based on the picture provided. Let's think through each option. Let's think step by step."

prompt_format: 
  - |
    Question: {}
    (A) {}
    (B) {}
    (C) {}
    (D) {}
    (E) {}
    (F) {}
    Explanation: 
    Answer:
    